### ISSUE TITLE
Update existing DOIs with licensing information

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/doi-service#226]
See parent story for details on the licensing information to include

**Comment by jordanpadams** [comment]
@alexdunnjpl this is on deck. would like to use [the Jupyter notebook here](https://github.com/NASA-PDS/doi-service/tree/main/src/pds_doi_service/notebooks) (or whatever you would prefer) to update the existing PDS DOI metadata with this new rightsList metadata

**Comment by jordanpadams** [comment]
@alexdunnjpl have you had a chance to take a look at this?

**Comment by jordanpadams** [comment]
if not, this is next up

**Comment by alexdunnjpl** [comment]
@jordanpadams missed your comment from a month ago - will take a look at this tomorrow/Friday

**Comment by alexdunnjpl** [comment]
@jordanpadams in-prog.  Should be done in <30min.

Because of the way doi-service is set up (no update without release) I've limited this to only hit DOIs which are currently findable.

Unaffected DOIs will end up with the correct rights information upon release, iff the releaser is using a current version of doi-service (ie post- #357 )
