### ISSUE TITLE
As a DOI user, I would like to know the copyright for PDS data

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/doi-service#335]
## 💪 Motivation
...so that I can understand how I am allowed to use this data.

### AC1: New DOI
**Given** a data set requiring a new DOI
**When I perform** the steps to create a DOI
**Then I expect** "US Government Works" copyright included in the DOI metadata submitted to DataCite

### AC2: Update existing DOI
**Given** an existing DOI that was created prior to this ticket creation
**When I perform** a query for the DOI
**Then I expect** "US Government Works" copyright has been updated and included in the DOI metadata

**Comment by alexdunnjpl** [comment]
@jordanpadams please confirm exact desired text. Suggest:

> This is a work of the U.S. Government and is not
> subject to copyright protection in the United
> States. Foreign copyrights may apply.

**Comment by alexdunnjpl** [comment]
@jordanpadams @nutjob4life is it known to be possible to submit metadata that is a superset of the schema?  

[The schema](https://schema.datacite.org/meta/kernel-4.4/doc/DataCite-MetadataKernel_v4.4.pdf) does not explicitly provide for a copyright attribute (though I'm open to correction on that, since it seems weird for it not to and I just ctrl-f'd "copyright").

I've implemented the metadata attribute in 489b0ff244197279366c8aa4055d34512e7ef155 and confirmed that it's included in the outgoing json payload, but the returned DataCite DOI record does not include the attribute, which would be consistent with the submissions being filtered through the official schema.

**Comment by nutjob4life** [comment]
Maybe in [that schema](https://schema.datacite.org/meta/kernel-4.4/doc/DataCite-MetadataKernel_v4.4.pdf) the `Rights` slot (№16) could be used for copyright. It mentions:

> Provide a rights management statement for the resource…Include embargo information if applicable.

It goes onto list `Creative Commons` and `Apache` as example values, but I could see having more complex copyright statements, ITAR conditions, warranty on use, etc., in there.

**Comment by alexdunnjpl** [comment]
@nutjob4life oh good pickup, thanks for that 🙏

**Comment by alexdunnjpl** [comment]
@jordanpadams taking a final pass of this issue, I realize I've missed AC2.

I'd suggest that the desired functionality should be that copyright metadata should be updated when-and-only-when an update action is performed, rather than when the DOI is queried.

Please confirm.

**Comment by jordanpadams** [comment]
@alexdunnjpl sorry for the lack of clarity on AC2. The intent there was to use something like the [Bulk Record Update notebook](https://github.com/NASA-PDS/doi-service/blob/main/src/pds_doi_service/notebooks/Bulk%20Record%20Update.ipynb) to go back and update all existing DOIs with this copyright ([and licensing](https://github.com/NASA-PDS/doi-service/issues/224)) information. The AC2 is really just how someone could query a DOI that already exists and see this info is there.

**Comment by alexdunnjpl** [comment]
Behaviour as-implemented:

 - new DOIs get GWorks and CC0 by default
 - `release` applied with no `rightsList` attribute present in label data gets GWorks and CC0
 - `release` applied with empty or other-valued `rightsList` attribute in label data gets whatever the label specifies.
