### ISSUE TITLE
DOI Service does not accurately parse <author_list> and <editor_list> in XML labels

### ISSUE THREAD

**Issue by rsjoyner** [NASA-PDS/doi-service#377]
## 🐛 Describe the bug

When parsing the <author_list> and <editor_list> in PDS4 XML labels, a wobbly is thrown if the value doesn't follow the formation rules for using commas and semicolons.  For instance, this series of values will fail:

<author_list>smith, john; jones, tom, NASA; Google, Inc.</author_list>

(1) NASA will throw a wobbly because there is no comma 
(2) Google will be parsed inaccurately as <last_name>, <first_name>

## 📜 To Reproduce
See example above

## 🕵️ Expected behavior

(1) Allow a value (within the set of values) to not require a comma.
(2) A more difficult fix will be to "interpret" the Google example.

## 📚 Version of Software Used

N/A

## 🖥 System Info

---

## ⚙️ Engineering Details
Per @jordanpadams let's try to better handle case (1), but I don't think we will ever be able to handle case (2) until the PDS4 Information Model is improved.

**Comment by alexdunnjpl** [comment]
Per [PDS4 Information Model](https://pds.nasa.gov/datastandards/documents/im/v1/index_1I00.html#attribute_pds_citation_information_pds_author_list)

> The author_list attribute contains a semi-colon-separated list of names of people to be cited as authors of the associated product. The general format for individual names is: SURNAME, GIVEN NAME(s). Initials may be used in lieu of given name(s). If the name contains a suffix ("Jr.", "Sr.", "III", etc.) it should be placed before the comma (,). Do not include the word "and" before the final author. All authors should be listed explicitly - do not elide the list using "et al.". 

Current information model doesn't appear to allow for the possibility of organisation/mononym authors.  @jordanpadams, that seems like an oversight worth fixing.

Provided value `smith, john; jones, tom, NASA; Google, Inc.` does not fail, and produces expected results.
Value `smith, john; jones, tom; NASA; Google, Inc.` does fail due to `NASA` mononym.

Will fix, such that mononym values are written to the author last-name field, with a blank first-name field (if that doesn't cause validation problems - need to check).

**Comment by alexdunnjpl** [comment]
@jordanpadams is there a good reason the name parsing logic considers `.` to be a valid separator?  Does this support a known use-case?

**Comment by alexdunnjpl** [comment]
@jordanpadams existing tests suggest a need to support format `A.Dunn`.  Is this correct?  Seems like we should be able to expect people to input valid values, which I'd argue that isn't, but maybe there's something preventing us from being that opinionated?

**Comment by alexdunnjpl** [comment]
Final list of supported formats:

```
[
    "A. Dunn",
    "Dunn, Alex",
    "Dunn, A.",
    "Dunn, A. E.",
    "Dunn, A. E. F. G.",
    "Dunn, Alexander E.",
    "Dunn, Alexander E. F. G.",
    "Jet Propulsion Laboratory",
    "JPL",
    "Google Inc.",
    "Suffixed Jr., James",
]
```
